# pull official base image
FROM python:3.8.3-alpine

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1 # Prevents Python from writing pyc files to disc. (equivalent to python -B option)
ENV PYTHONUNBUFFERED 1 # Prevents Python from buffering stdout and stderr. (equivalent to python -u option)

# install postgres dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.dev.sh .

# copy project
COPY . .

# run entrypoint.sh
RUN chmod +x /usr/src/app/compose/entrypoint.dev.sh

ENTRYPOINT ["/usr/src/app/compose/entrypoint.dev.sh"]