# Generated by Django 3.1 on 2022-12-16 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_user_account_email_activation', models.BooleanField(help_text='If checked, users will activate their accounts via email')),
                ('account_activation_url', models.CharField(default='http://0.0.0.0:8080/#/dashboard/activate/', help_text='Url sent to user to activate his account. Uid and token will be appended to the url', max_length=255)),
                ('change_password_url', models.CharField(default='http://0.0.0.0:8080/#/dashboard/forgotpassword/', help_text='Url sent to user to reset his password. Uid and token will be appended to the url', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'User Settings',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date user signed up', verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Has access to the admin panel'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Is a super user'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_upload_custom_shapefile',
            field=models.BooleanField(default=False, help_text='Can user upload custom shapefiles'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_upload_standard_raster',
            field=models.BooleanField(default=False, help_text='Can user upload standard rasters'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(help_text='Institution', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(help_text='Profession', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(help_text='Designation', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
