# Generated by Django 3.1 on 2023-01-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20230113_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationlog',
            options={'verbose_name_plural': 'Communication Log'},
        ),
        migrations.AlterModelOptions(
            name='communicationsettings',
            options={'verbose_name_plural': 'Communication Settings'},
        ),
    ]
